name: Build debug
on: [push, pull_request, workflow_dispatch]

jobs:
  build-desktop:
    name: Build [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: proxySpeedTestApp_win
            arch: 'x86'
            spec: pyinstaller.spec
          - os: ubuntu-latest
            name: proxySpeedTestApp_linux
            arch: ''
            spec: pyinstallerL.spec
            
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: ${{ matrix.arch }}
    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install git+https://github.com/pyinstaller/pyinstaller@0f2b2e921433ab5a510c7efdb21d9c1d7cfbc645
    - name: Install dependencies
      run: |
        pip install Pillow opencv-python pyenchant requests pysocks hurry.filesize ago urllib3 https://github.com/kivymd/KivyMD/archive/refs/heads/master.zip kivy==2.0.0
    - name: Build with pyinstaller for ${{matrix.name}}
      run: pyinstaller ${{matrix.spec}}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package_windows_${{ matrix.name }}
        path: ./dist/
    

  # Build job. Builds every demo app for Android with Buildozer
  build-android:
    name: Build Android [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        name: [proxySpeedTestApp]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: master
        buildozer_version: master
        command: buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.name }}
        path: ${{ steps.buildozer.outputs.filename }}
    
#     - name: Changing permission
#       run: |
#         sudo chown -R $(whoami): .

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         path: data
#         ref: screenshort # Branch name
#         persist-credentials: false
    
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7
#         architecture: x64

#     - name: Push binary to screenshort branch
#       run: |
#         #Use personal token to push (when using GITHUB_TOKEN, it will not allow pushes from PR)
#         cd data && \
#           git config user.name "biplobsd" && \
#           git config user.email biplobsd11@gmail.com && \
#           git remote set-url origin https://biplobsd:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} && \
#           cd ..
#         python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data apk
