name: Build debug apk
on: [push, pull_request]

jobs:
  # Build job. Builds every demo app for Android with Buildozer
  build-android:
    name: Build Android [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        name: [proxySpeedTestApp]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: master
        command: buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.name }}
        path: ${{ steps.buildozer.outputs.filename }}
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: apk
        ref: screenshort # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master screenshort
