name: Build debug apk
on: [push, pull_request]

jobs:
  build-windows:
    name: Build Windows [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        name: [proxySpeedTestApp]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
          pip install -U setuptools wheel
          pip install git+https://github.com/pyinstaller/pyinstaller@develop
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pysocks hurry.filesize ago urllib3 Pillow https://github.com/kivymd/KivyMD/archive/refs/heads/master.zip kivy==2.0.0
    - name: Build with pyinstaller for ${{matrix.name}}
      run: pyinstaller pyinstaller.spec
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.name }}
        path: ./dist/*.exe
    

  # Build job. Builds every demo app for Android with Buildozer
  build-android:
    name: Build Android [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        name: [proxySpeedTestApp]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: master
        buildozer_version: master
        command: buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.name }}
        path: ${{ steps.buildozer.outputs.filename }}
    
#     - name: Changing permission
#       run: |
#         sudo chown -R $(whoami): .

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         path: data
#         ref: screenshort # Branch name
#         persist-credentials: false
    
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7
#         architecture: x64

#     - name: Push binary to screenshort branch
#       run: |
#         #Use personal token to push (when using GITHUB_TOKEN, it will not allow pushes from PR)
#         cd data && \
#           git config user.name "biplobsd" && \
#           git config user.email biplobsd11@gmail.com && \
#           git remote set-url origin https://biplobsd:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} && \
#           cd ..
#         python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data apk
